// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
		{Name: "action", Type: field.TypeString, Size: 120},
		{Name: "target_type", Type: field.TypeString, Nullable: true, Size: 80},
		{Name: "target_id", Type: field.TypeString, Nullable: true, Size: 80},
		{Name: "ip", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "details", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
	}
	// JobsColumns holds the columns for the "jobs" table.
	JobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "job_key", Type: field.TypeString, Size: 80},
		{Name: "type", Type: field.TypeString, Size: 80},
		{Name: "status", Type: field.TypeString, Default: "queued"},
		{Name: "progress", Type: field.TypeInt, Default: 0},
		{Name: "message", Type: field.TypeString, Nullable: true, Size: 2000},
		{Name: "payload", Type: field.TypeJSON, Nullable: true},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// JobsTable holds the schema information for the "jobs" table.
	JobsTable = &schema.Table{
		Name:       "jobs",
		Columns:    JobsColumns,
		PrimaryKey: []*schema.Column{JobsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "job_job_key",
				Unique:  true,
				Columns: []*schema.Column{JobsColumns[1]},
			},
		},
	}
	// ResourcesColumns holds the columns for the "resources" table.
	ResourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString, Size: 16},
		{Name: "name", Type: field.TypeString, Size: 120},
		{Name: "host", Type: field.TypeString, Size: 255},
		{Name: "management_url", Type: field.TypeString, Nullable: true, Size: 1024},
		{Name: "access_token_ciphertext", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "unknown"},
		{Name: "node_count", Type: field.TypeInt, Default: 0},
		{Name: "client_count", Type: field.TypeInt, Default: 0},
		{Name: "socks_count", Type: field.TypeInt, Default: 0},
		{Name: "latency_ms", Type: field.TypeInt, Default: 0},
		{Name: "last_checked_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ResourcesTable holds the schema information for the "resources" table.
	ResourcesTable = &schema.Table{
		Name:       "resources",
		Columns:    ResourcesColumns,
		PrimaryKey: []*schema.Column{ResourcesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "resource_code",
				Unique:  true,
				Columns: []*schema.Column{ResourcesColumns[1]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Size: 64},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeString, Default: "admin"},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "must_change_password", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuditLogsTable,
		JobsTable,
		ResourcesTable,
		UsersTable,
	}
)

func init() {
}
