// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zhou1h/3xui-network-panel-v2/ent/auditlog"
	"github.com/zhou1h/3xui-network-panel-v2/ent/predicate"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuditLogUpdate) SetUserID(v int) *AuditLogUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableUserID(v *int) *AuditLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AuditLogUpdate) AddUserID(v int) *AuditLogUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AuditLogUpdate) ClearUserID() *AuditLogUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdate) SetAction(v string) *AuditLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableAction(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *AuditLogUpdate) SetTargetType(v string) *AuditLogUpdate {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableTargetType(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// ClearTargetType clears the value of the "target_type" field.
func (_u *AuditLogUpdate) ClearTargetType() *AuditLogUpdate {
	_u.mutation.ClearTargetType()
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *AuditLogUpdate) SetTargetID(v string) *AuditLogUpdate {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableTargetID(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// ClearTargetID clears the value of the "target_id" field.
func (_u *AuditLogUpdate) ClearTargetID() *AuditLogUpdate {
	_u.mutation.ClearTargetID()
	return _u
}

// SetIP sets the "ip" field.
func (_u *AuditLogUpdate) SetIP(v string) *AuditLogUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableIP(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *AuditLogUpdate) ClearIP() *AuditLogUpdate {
	_u.mutation.ClearIP()
	return _u
}

// SetDetails sets the "details" field.
func (_u *AuditLogUpdate) SetDetails(v map[string]interface{}) *AuditLogUpdate {
	_u.mutation.SetDetails(v)
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *AuditLogUpdate) ClearDetails() *AuditLogUpdate {
	_u.mutation.ClearDetails()
	return _u
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdate) Mutation() *AuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetType(); ok {
		if err := auditlog.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.target_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetID(); ok {
		if err := auditlog.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.target_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IP(); ok {
		if err := auditlog.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "AuditLog.ip": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(auditlog.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(auditlog.FieldUserID, field.TypeInt, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(auditlog.FieldUserID, field.TypeInt)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(auditlog.FieldTargetType, field.TypeString, value)
	}
	if _u.mutation.TargetTypeCleared() {
		_spec.ClearField(auditlog.FieldTargetType, field.TypeString)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(auditlog.FieldTargetID, field.TypeString, value)
	}
	if _u.mutation.TargetIDCleared() {
		_spec.ClearField(auditlog.FieldTargetID, field.TypeString)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(auditlog.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(auditlog.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(auditlog.FieldDetails, field.TypeJSON, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(auditlog.FieldDetails, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetUserID sets the "user_id" field.
func (_u *AuditLogUpdateOne) SetUserID(v int) *AuditLogUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableUserID(v *int) *AuditLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AuditLogUpdateOne) AddUserID(v int) *AuditLogUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AuditLogUpdateOne) ClearUserID() *AuditLogUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdateOne) SetAction(v string) *AuditLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableAction(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *AuditLogUpdateOne) SetTargetType(v string) *AuditLogUpdateOne {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableTargetType(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// ClearTargetType clears the value of the "target_type" field.
func (_u *AuditLogUpdateOne) ClearTargetType() *AuditLogUpdateOne {
	_u.mutation.ClearTargetType()
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *AuditLogUpdateOne) SetTargetID(v string) *AuditLogUpdateOne {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableTargetID(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// ClearTargetID clears the value of the "target_id" field.
func (_u *AuditLogUpdateOne) ClearTargetID() *AuditLogUpdateOne {
	_u.mutation.ClearTargetID()
	return _u
}

// SetIP sets the "ip" field.
func (_u *AuditLogUpdateOne) SetIP(v string) *AuditLogUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableIP(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *AuditLogUpdateOne) ClearIP() *AuditLogUpdateOne {
	_u.mutation.ClearIP()
	return _u
}

// SetDetails sets the "details" field.
func (_u *AuditLogUpdateOne) SetDetails(v map[string]interface{}) *AuditLogUpdateOne {
	_u.mutation.SetDetails(v)
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *AuditLogUpdateOne) ClearDetails() *AuditLogUpdateOne {
	_u.mutation.ClearDetails()
	return _u
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditLog entity.
func (_u *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetType(); ok {
		if err := auditlog.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.target_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetID(); ok {
		if err := auditlog.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.target_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IP(); ok {
		if err := auditlog.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "AuditLog.ip": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(auditlog.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(auditlog.FieldUserID, field.TypeInt, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(auditlog.FieldUserID, field.TypeInt)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(auditlog.FieldTargetType, field.TypeString, value)
	}
	if _u.mutation.TargetTypeCleared() {
		_spec.ClearField(auditlog.FieldTargetType, field.TypeString)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(auditlog.FieldTargetID, field.TypeString, value)
	}
	if _u.mutation.TargetIDCleared() {
		_spec.ClearField(auditlog.FieldTargetID, field.TypeString)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(auditlog.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(auditlog.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(auditlog.FieldDetails, field.TypeJSON, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(auditlog.FieldDetails, field.TypeJSON)
	}
	_node = &AuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
