// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zhou1h/3xui-network-panel-v2/ent/job"
	"github.com/zhou1h/3xui-network-panel-v2/ent/predicate"
)

// JobUpdate is the builder for updating Job entities.
type JobUpdate struct {
	config
	hooks    []Hook
	mutation *JobMutation
}

// Where appends a list predicates to the JobUpdate builder.
func (_u *JobUpdate) Where(ps ...predicate.Job) *JobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetJobKey sets the "job_key" field.
func (_u *JobUpdate) SetJobKey(v string) *JobUpdate {
	_u.mutation.SetJobKey(v)
	return _u
}

// SetNillableJobKey sets the "job_key" field if the given value is not nil.
func (_u *JobUpdate) SetNillableJobKey(v *string) *JobUpdate {
	if v != nil {
		_u.SetJobKey(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *JobUpdate) SetType(v string) *JobUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *JobUpdate) SetNillableType(v *string) *JobUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobUpdate) SetStatus(v string) *JobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobUpdate) SetNillableStatus(v *string) *JobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProgress sets the "progress" field.
func (_u *JobUpdate) SetProgress(v int) *JobUpdate {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *JobUpdate) SetNillableProgress(v *int) *JobUpdate {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *JobUpdate) AddProgress(v int) *JobUpdate {
	_u.mutation.AddProgress(v)
	return _u
}

// SetMessage sets the "message" field.
func (_u *JobUpdate) SetMessage(v string) *JobUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *JobUpdate) SetNillableMessage(v *string) *JobUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *JobUpdate) ClearMessage() *JobUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *JobUpdate) SetPayload(v map[string]interface{}) *JobUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *JobUpdate) ClearPayload() *JobUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *JobUpdate) SetStartedAt(v time.Time) *JobUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *JobUpdate) SetNillableStartedAt(v *time.Time) *JobUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *JobUpdate) ClearStartedAt() *JobUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *JobUpdate) SetFinishedAt(v time.Time) *JobUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *JobUpdate) SetNillableFinishedAt(v *time.Time) *JobUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *JobUpdate) ClearFinishedAt() *JobUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *JobUpdate) SetUpdatedAt(v time.Time) *JobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the JobMutation object of the builder.
func (_u *JobUpdate) Mutation() *JobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *JobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *JobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *JobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := job.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JobUpdate) check() error {
	if v, ok := _u.mutation.JobKey(); ok {
		if err := job.JobKeyValidator(v); err != nil {
			return &ValidationError{Name: "job_key", err: fmt.Errorf(`ent: validator failed for field "Job.job_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := job.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Job.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := job.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Job.message": %w`, err)}
		}
	}
	return nil
}

func (_u *JobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JobKey(); ok {
		_spec.SetField(job.FieldJobKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(job.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(job.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(job.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(job.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(job.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(job.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(job.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(job.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(job.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(job.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(job.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(job.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// JobUpdateOne is the builder for updating a single Job entity.
type JobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobMutation
}

// SetJobKey sets the "job_key" field.
func (_u *JobUpdateOne) SetJobKey(v string) *JobUpdateOne {
	_u.mutation.SetJobKey(v)
	return _u
}

// SetNillableJobKey sets the "job_key" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableJobKey(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetJobKey(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *JobUpdateOne) SetType(v string) *JobUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableType(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobUpdateOne) SetStatus(v string) *JobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableStatus(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProgress sets the "progress" field.
func (_u *JobUpdateOne) SetProgress(v int) *JobUpdateOne {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableProgress(v *int) *JobUpdateOne {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *JobUpdateOne) AddProgress(v int) *JobUpdateOne {
	_u.mutation.AddProgress(v)
	return _u
}

// SetMessage sets the "message" field.
func (_u *JobUpdateOne) SetMessage(v string) *JobUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableMessage(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *JobUpdateOne) ClearMessage() *JobUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *JobUpdateOne) SetPayload(v map[string]interface{}) *JobUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *JobUpdateOne) ClearPayload() *JobUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *JobUpdateOne) SetStartedAt(v time.Time) *JobUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableStartedAt(v *time.Time) *JobUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *JobUpdateOne) ClearStartedAt() *JobUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *JobUpdateOne) SetFinishedAt(v time.Time) *JobUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableFinishedAt(v *time.Time) *JobUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *JobUpdateOne) ClearFinishedAt() *JobUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *JobUpdateOne) SetUpdatedAt(v time.Time) *JobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the JobMutation object of the builder.
func (_u *JobUpdateOne) Mutation() *JobMutation {
	return _u.mutation
}

// Where appends a list predicates to the JobUpdate builder.
func (_u *JobUpdateOne) Where(ps ...predicate.Job) *JobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *JobUpdateOne) Select(field string, fields ...string) *JobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Job entity.
func (_u *JobUpdateOne) Save(ctx context.Context) (*Job, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobUpdateOne) SaveX(ctx context.Context) *Job {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *JobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *JobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := job.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JobUpdateOne) check() error {
	if v, ok := _u.mutation.JobKey(); ok {
		if err := job.JobKeyValidator(v); err != nil {
			return &ValidationError{Name: "job_key", err: fmt.Errorf(`ent: validator failed for field "Job.job_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := job.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Job.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := job.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Job.message": %w`, err)}
		}
	}
	return nil
}

func (_u *JobUpdateOne) sqlSave(ctx context.Context) (_node *Job, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Job.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, job.FieldID)
		for _, f := range fields {
			if !job.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != job.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JobKey(); ok {
		_spec.SetField(job.FieldJobKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(job.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(job.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(job.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(job.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(job.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(job.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(job.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(job.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(job.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(job.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(job.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(job.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Job{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
