// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zhou1h/3xui-network-panel-v2/ent/predicate"
	"github.com/zhou1h/3xui-network-panel-v2/ent/resource"
)

// ResourceUpdate is the builder for updating Resource entities.
type ResourceUpdate struct {
	config
	hooks    []Hook
	mutation *ResourceMutation
}

// Where appends a list predicates to the ResourceUpdate builder.
func (_u *ResourceUpdate) Where(ps ...predicate.Resource) *ResourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *ResourceUpdate) SetCode(v string) *ResourceUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableCode(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ResourceUpdate) SetName(v string) *ResourceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableName(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *ResourceUpdate) SetHost(v string) *ResourceUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableHost(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetManagementURL sets the "management_url" field.
func (_u *ResourceUpdate) SetManagementURL(v string) *ResourceUpdate {
	_u.mutation.SetManagementURL(v)
	return _u
}

// SetNillableManagementURL sets the "management_url" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableManagementURL(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetManagementURL(*v)
	}
	return _u
}

// ClearManagementURL clears the value of the "management_url" field.
func (_u *ResourceUpdate) ClearManagementURL() *ResourceUpdate {
	_u.mutation.ClearManagementURL()
	return _u
}

// SetAccessTokenCiphertext sets the "access_token_ciphertext" field.
func (_u *ResourceUpdate) SetAccessTokenCiphertext(v string) *ResourceUpdate {
	_u.mutation.SetAccessTokenCiphertext(v)
	return _u
}

// SetNillableAccessTokenCiphertext sets the "access_token_ciphertext" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableAccessTokenCiphertext(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetAccessTokenCiphertext(*v)
	}
	return _u
}

// ClearAccessTokenCiphertext clears the value of the "access_token_ciphertext" field.
func (_u *ResourceUpdate) ClearAccessTokenCiphertext() *ResourceUpdate {
	_u.mutation.ClearAccessTokenCiphertext()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResourceUpdate) SetStatus(v string) *ResourceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableStatus(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNodeCount sets the "node_count" field.
func (_u *ResourceUpdate) SetNodeCount(v int) *ResourceUpdate {
	_u.mutation.ResetNodeCount()
	_u.mutation.SetNodeCount(v)
	return _u
}

// SetNillableNodeCount sets the "node_count" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableNodeCount(v *int) *ResourceUpdate {
	if v != nil {
		_u.SetNodeCount(*v)
	}
	return _u
}

// AddNodeCount adds value to the "node_count" field.
func (_u *ResourceUpdate) AddNodeCount(v int) *ResourceUpdate {
	_u.mutation.AddNodeCount(v)
	return _u
}

// SetClientCount sets the "client_count" field.
func (_u *ResourceUpdate) SetClientCount(v int) *ResourceUpdate {
	_u.mutation.ResetClientCount()
	_u.mutation.SetClientCount(v)
	return _u
}

// SetNillableClientCount sets the "client_count" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableClientCount(v *int) *ResourceUpdate {
	if v != nil {
		_u.SetClientCount(*v)
	}
	return _u
}

// AddClientCount adds value to the "client_count" field.
func (_u *ResourceUpdate) AddClientCount(v int) *ResourceUpdate {
	_u.mutation.AddClientCount(v)
	return _u
}

// SetSocksCount sets the "socks_count" field.
func (_u *ResourceUpdate) SetSocksCount(v int) *ResourceUpdate {
	_u.mutation.ResetSocksCount()
	_u.mutation.SetSocksCount(v)
	return _u
}

// SetNillableSocksCount sets the "socks_count" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableSocksCount(v *int) *ResourceUpdate {
	if v != nil {
		_u.SetSocksCount(*v)
	}
	return _u
}

// AddSocksCount adds value to the "socks_count" field.
func (_u *ResourceUpdate) AddSocksCount(v int) *ResourceUpdate {
	_u.mutation.AddSocksCount(v)
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *ResourceUpdate) SetLatencyMs(v int) *ResourceUpdate {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableLatencyMs(v *int) *ResourceUpdate {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *ResourceUpdate) AddLatencyMs(v int) *ResourceUpdate {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *ResourceUpdate) SetLastCheckedAt(v time.Time) *ResourceUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableLastCheckedAt(v *time.Time) *ResourceUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *ResourceUpdate) ClearLastCheckedAt() *ResourceUpdate {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourceUpdate) SetUpdatedAt(v time.Time) *ResourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ResourceMutation object of the builder.
func (_u *ResourceUpdate) Mutation() *ResourceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResourceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := resource.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Resource.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := resource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Resource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := resource.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Resource.host": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ManagementURL(); ok {
		if err := resource.ManagementURLValidator(v); err != nil {
			return &ValidationError{Name: "management_url", err: fmt.Errorf(`ent: validator failed for field "Resource.management_url": %w`, err)}
		}
	}
	return nil
}

func (_u *ResourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resource.Table, resource.Columns, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(resource.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(resource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(resource.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManagementURL(); ok {
		_spec.SetField(resource.FieldManagementURL, field.TypeString, value)
	}
	if _u.mutation.ManagementURLCleared() {
		_spec.ClearField(resource.FieldManagementURL, field.TypeString)
	}
	if value, ok := _u.mutation.AccessTokenCiphertext(); ok {
		_spec.SetField(resource.FieldAccessTokenCiphertext, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCiphertextCleared() {
		_spec.ClearField(resource.FieldAccessTokenCiphertext, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resource.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeCount(); ok {
		_spec.SetField(resource.FieldNodeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNodeCount(); ok {
		_spec.AddField(resource.FieldNodeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ClientCount(); ok {
		_spec.SetField(resource.FieldClientCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClientCount(); ok {
		_spec.AddField(resource.FieldClientCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SocksCount(); ok {
		_spec.SetField(resource.FieldSocksCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSocksCount(); ok {
		_spec.AddField(resource.FieldSocksCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(resource.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(resource.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(resource.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(resource.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resource.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResourceUpdateOne is the builder for updating a single Resource entity.
type ResourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResourceMutation
}

// SetCode sets the "code" field.
func (_u *ResourceUpdateOne) SetCode(v string) *ResourceUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableCode(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ResourceUpdateOne) SetName(v string) *ResourceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableName(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *ResourceUpdateOne) SetHost(v string) *ResourceUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableHost(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetManagementURL sets the "management_url" field.
func (_u *ResourceUpdateOne) SetManagementURL(v string) *ResourceUpdateOne {
	_u.mutation.SetManagementURL(v)
	return _u
}

// SetNillableManagementURL sets the "management_url" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableManagementURL(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetManagementURL(*v)
	}
	return _u
}

// ClearManagementURL clears the value of the "management_url" field.
func (_u *ResourceUpdateOne) ClearManagementURL() *ResourceUpdateOne {
	_u.mutation.ClearManagementURL()
	return _u
}

// SetAccessTokenCiphertext sets the "access_token_ciphertext" field.
func (_u *ResourceUpdateOne) SetAccessTokenCiphertext(v string) *ResourceUpdateOne {
	_u.mutation.SetAccessTokenCiphertext(v)
	return _u
}

// SetNillableAccessTokenCiphertext sets the "access_token_ciphertext" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableAccessTokenCiphertext(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetAccessTokenCiphertext(*v)
	}
	return _u
}

// ClearAccessTokenCiphertext clears the value of the "access_token_ciphertext" field.
func (_u *ResourceUpdateOne) ClearAccessTokenCiphertext() *ResourceUpdateOne {
	_u.mutation.ClearAccessTokenCiphertext()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResourceUpdateOne) SetStatus(v string) *ResourceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableStatus(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNodeCount sets the "node_count" field.
func (_u *ResourceUpdateOne) SetNodeCount(v int) *ResourceUpdateOne {
	_u.mutation.ResetNodeCount()
	_u.mutation.SetNodeCount(v)
	return _u
}

// SetNillableNodeCount sets the "node_count" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableNodeCount(v *int) *ResourceUpdateOne {
	if v != nil {
		_u.SetNodeCount(*v)
	}
	return _u
}

// AddNodeCount adds value to the "node_count" field.
func (_u *ResourceUpdateOne) AddNodeCount(v int) *ResourceUpdateOne {
	_u.mutation.AddNodeCount(v)
	return _u
}

// SetClientCount sets the "client_count" field.
func (_u *ResourceUpdateOne) SetClientCount(v int) *ResourceUpdateOne {
	_u.mutation.ResetClientCount()
	_u.mutation.SetClientCount(v)
	return _u
}

// SetNillableClientCount sets the "client_count" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableClientCount(v *int) *ResourceUpdateOne {
	if v != nil {
		_u.SetClientCount(*v)
	}
	return _u
}

// AddClientCount adds value to the "client_count" field.
func (_u *ResourceUpdateOne) AddClientCount(v int) *ResourceUpdateOne {
	_u.mutation.AddClientCount(v)
	return _u
}

// SetSocksCount sets the "socks_count" field.
func (_u *ResourceUpdateOne) SetSocksCount(v int) *ResourceUpdateOne {
	_u.mutation.ResetSocksCount()
	_u.mutation.SetSocksCount(v)
	return _u
}

// SetNillableSocksCount sets the "socks_count" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableSocksCount(v *int) *ResourceUpdateOne {
	if v != nil {
		_u.SetSocksCount(*v)
	}
	return _u
}

// AddSocksCount adds value to the "socks_count" field.
func (_u *ResourceUpdateOne) AddSocksCount(v int) *ResourceUpdateOne {
	_u.mutation.AddSocksCount(v)
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *ResourceUpdateOne) SetLatencyMs(v int) *ResourceUpdateOne {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableLatencyMs(v *int) *ResourceUpdateOne {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *ResourceUpdateOne) AddLatencyMs(v int) *ResourceUpdateOne {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *ResourceUpdateOne) SetLastCheckedAt(v time.Time) *ResourceUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableLastCheckedAt(v *time.Time) *ResourceUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *ResourceUpdateOne) ClearLastCheckedAt() *ResourceUpdateOne {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourceUpdateOne) SetUpdatedAt(v time.Time) *ResourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ResourceMutation object of the builder.
func (_u *ResourceUpdateOne) Mutation() *ResourceMutation {
	return _u.mutation
}

// Where appends a list predicates to the ResourceUpdate builder.
func (_u *ResourceUpdateOne) Where(ps ...predicate.Resource) *ResourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResourceUpdateOne) Select(field string, fields ...string) *ResourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Resource entity.
func (_u *ResourceUpdateOne) Save(ctx context.Context) (*Resource, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceUpdateOne) SaveX(ctx context.Context) *Resource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := resource.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Resource.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := resource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Resource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := resource.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Resource.host": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ManagementURL(); ok {
		if err := resource.ManagementURLValidator(v); err != nil {
			return &ValidationError{Name: "management_url", err: fmt.Errorf(`ent: validator failed for field "Resource.management_url": %w`, err)}
		}
	}
	return nil
}

func (_u *ResourceUpdateOne) sqlSave(ctx context.Context) (_node *Resource, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resource.Table, resource.Columns, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Resource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resource.FieldID)
		for _, f := range fields {
			if !resource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(resource.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(resource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(resource.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManagementURL(); ok {
		_spec.SetField(resource.FieldManagementURL, field.TypeString, value)
	}
	if _u.mutation.ManagementURLCleared() {
		_spec.ClearField(resource.FieldManagementURL, field.TypeString)
	}
	if value, ok := _u.mutation.AccessTokenCiphertext(); ok {
		_spec.SetField(resource.FieldAccessTokenCiphertext, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCiphertextCleared() {
		_spec.ClearField(resource.FieldAccessTokenCiphertext, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resource.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeCount(); ok {
		_spec.SetField(resource.FieldNodeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNodeCount(); ok {
		_spec.AddField(resource.FieldNodeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ClientCount(); ok {
		_spec.SetField(resource.FieldClientCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClientCount(); ok {
		_spec.AddField(resource.FieldClientCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SocksCount(); ok {
		_spec.SetField(resource.FieldSocksCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSocksCount(); ok {
		_spec.AddField(resource.FieldSocksCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(resource.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(resource.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(resource.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(resource.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resource.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Resource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
