// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/zhou1h/3xui-network-panel-v2/ent/resource"
)

// Resource is the model entity for the Resource schema.
type Resource struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Host holds the value of the "host" field.
	Host string `json:"host,omitempty"`
	// ManagementURL holds the value of the "management_url" field.
	ManagementURL string `json:"management_url,omitempty"`
	// AccessTokenCiphertext holds the value of the "access_token_ciphertext" field.
	AccessTokenCiphertext string `json:"-"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// NodeCount holds the value of the "node_count" field.
	NodeCount int `json:"node_count,omitempty"`
	// ClientCount holds the value of the "client_count" field.
	ClientCount int `json:"client_count,omitempty"`
	// SocksCount holds the value of the "socks_count" field.
	SocksCount int `json:"socks_count,omitempty"`
	// LatencyMs holds the value of the "latency_ms" field.
	LatencyMs int `json:"latency_ms,omitempty"`
	// LastCheckedAt holds the value of the "last_checked_at" field.
	LastCheckedAt *time.Time `json:"last_checked_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Resource) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resource.FieldID, resource.FieldNodeCount, resource.FieldClientCount, resource.FieldSocksCount, resource.FieldLatencyMs:
			values[i] = new(sql.NullInt64)
		case resource.FieldCode, resource.FieldName, resource.FieldHost, resource.FieldManagementURL, resource.FieldAccessTokenCiphertext, resource.FieldStatus:
			values[i] = new(sql.NullString)
		case resource.FieldLastCheckedAt, resource.FieldCreatedAt, resource.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Resource fields.
func (_m *Resource) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resource.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case resource.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case resource.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case resource.FieldHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host", values[i])
			} else if value.Valid {
				_m.Host = value.String
			}
		case resource.FieldManagementURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field management_url", values[i])
			} else if value.Valid {
				_m.ManagementURL = value.String
			}
		case resource.FieldAccessTokenCiphertext:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token_ciphertext", values[i])
			} else if value.Valid {
				_m.AccessTokenCiphertext = value.String
			}
		case resource.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case resource.FieldNodeCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field node_count", values[i])
			} else if value.Valid {
				_m.NodeCount = int(value.Int64)
			}
		case resource.FieldClientCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field client_count", values[i])
			} else if value.Valid {
				_m.ClientCount = int(value.Int64)
			}
		case resource.FieldSocksCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field socks_count", values[i])
			} else if value.Valid {
				_m.SocksCount = int(value.Int64)
			}
		case resource.FieldLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field latency_ms", values[i])
			} else if value.Valid {
				_m.LatencyMs = int(value.Int64)
			}
		case resource.FieldLastCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_checked_at", values[i])
			} else if value.Valid {
				_m.LastCheckedAt = new(time.Time)
				*_m.LastCheckedAt = value.Time
			}
		case resource.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case resource.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Resource.
// This includes values selected through modifiers, order, etc.
func (_m *Resource) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Resource.
// Note that you need to call Resource.Unwrap() before calling this method if this Resource
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Resource) Update() *ResourceUpdateOne {
	return NewResourceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Resource entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Resource) Unwrap() *Resource {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Resource is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Resource) String() string {
	var builder strings.Builder
	builder.WriteString("Resource(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("host=")
	builder.WriteString(_m.Host)
	builder.WriteString(", ")
	builder.WriteString("management_url=")
	builder.WriteString(_m.ManagementURL)
	builder.WriteString(", ")
	builder.WriteString("access_token_ciphertext=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("node_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.NodeCount))
	builder.WriteString(", ")
	builder.WriteString("client_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClientCount))
	builder.WriteString(", ")
	builder.WriteString("socks_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SocksCount))
	builder.WriteString(", ")
	builder.WriteString("latency_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.LatencyMs))
	builder.WriteString(", ")
	if v := _m.LastCheckedAt; v != nil {
		builder.WriteString("last_checked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Resources is a parsable slice of Resource.
type Resources []*Resource
