// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zhou1h/3xui-network-panel-v2/ent/resource"
)

// ResourceCreate is the builder for creating a Resource entity.
type ResourceCreate struct {
	config
	mutation *ResourceMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (_c *ResourceCreate) SetCode(v string) *ResourceCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ResourceCreate) SetName(v string) *ResourceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetHost sets the "host" field.
func (_c *ResourceCreate) SetHost(v string) *ResourceCreate {
	_c.mutation.SetHost(v)
	return _c
}

// SetManagementURL sets the "management_url" field.
func (_c *ResourceCreate) SetManagementURL(v string) *ResourceCreate {
	_c.mutation.SetManagementURL(v)
	return _c
}

// SetNillableManagementURL sets the "management_url" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableManagementURL(v *string) *ResourceCreate {
	if v != nil {
		_c.SetManagementURL(*v)
	}
	return _c
}

// SetAccessTokenCiphertext sets the "access_token_ciphertext" field.
func (_c *ResourceCreate) SetAccessTokenCiphertext(v string) *ResourceCreate {
	_c.mutation.SetAccessTokenCiphertext(v)
	return _c
}

// SetNillableAccessTokenCiphertext sets the "access_token_ciphertext" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableAccessTokenCiphertext(v *string) *ResourceCreate {
	if v != nil {
		_c.SetAccessTokenCiphertext(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ResourceCreate) SetStatus(v string) *ResourceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableStatus(v *string) *ResourceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNodeCount sets the "node_count" field.
func (_c *ResourceCreate) SetNodeCount(v int) *ResourceCreate {
	_c.mutation.SetNodeCount(v)
	return _c
}

// SetNillableNodeCount sets the "node_count" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableNodeCount(v *int) *ResourceCreate {
	if v != nil {
		_c.SetNodeCount(*v)
	}
	return _c
}

// SetClientCount sets the "client_count" field.
func (_c *ResourceCreate) SetClientCount(v int) *ResourceCreate {
	_c.mutation.SetClientCount(v)
	return _c
}

// SetNillableClientCount sets the "client_count" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableClientCount(v *int) *ResourceCreate {
	if v != nil {
		_c.SetClientCount(*v)
	}
	return _c
}

// SetSocksCount sets the "socks_count" field.
func (_c *ResourceCreate) SetSocksCount(v int) *ResourceCreate {
	_c.mutation.SetSocksCount(v)
	return _c
}

// SetNillableSocksCount sets the "socks_count" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableSocksCount(v *int) *ResourceCreate {
	if v != nil {
		_c.SetSocksCount(*v)
	}
	return _c
}

// SetLatencyMs sets the "latency_ms" field.
func (_c *ResourceCreate) SetLatencyMs(v int) *ResourceCreate {
	_c.mutation.SetLatencyMs(v)
	return _c
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableLatencyMs(v *int) *ResourceCreate {
	if v != nil {
		_c.SetLatencyMs(*v)
	}
	return _c
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_c *ResourceCreate) SetLastCheckedAt(v time.Time) *ResourceCreate {
	_c.mutation.SetLastCheckedAt(v)
	return _c
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableLastCheckedAt(v *time.Time) *ResourceCreate {
	if v != nil {
		_c.SetLastCheckedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResourceCreate) SetCreatedAt(v time.Time) *ResourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableCreatedAt(v *time.Time) *ResourceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResourceCreate) SetUpdatedAt(v time.Time) *ResourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableUpdatedAt(v *time.Time) *ResourceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ResourceMutation object of the builder.
func (_c *ResourceCreate) Mutation() *ResourceMutation {
	return _c.mutation
}

// Save creates the Resource in the database.
func (_c *ResourceCreate) Save(ctx context.Context) (*Resource, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResourceCreate) SaveX(ctx context.Context) *Resource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResourceCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := resource.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.NodeCount(); !ok {
		v := resource.DefaultNodeCount
		_c.mutation.SetNodeCount(v)
	}
	if _, ok := _c.mutation.ClientCount(); !ok {
		v := resource.DefaultClientCount
		_c.mutation.SetClientCount(v)
	}
	if _, ok := _c.mutation.SocksCount(); !ok {
		v := resource.DefaultSocksCount
		_c.mutation.SetSocksCount(v)
	}
	if _, ok := _c.mutation.LatencyMs(); !ok {
		v := resource.DefaultLatencyMs
		_c.mutation.SetLatencyMs(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := resource.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := resource.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResourceCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Resource.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := resource.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Resource.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Resource.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := resource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Resource.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Host(); !ok {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required field "Resource.host"`)}
	}
	if v, ok := _c.mutation.Host(); ok {
		if err := resource.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Resource.host": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ManagementURL(); ok {
		if err := resource.ManagementURLValidator(v); err != nil {
			return &ValidationError{Name: "management_url", err: fmt.Errorf(`ent: validator failed for field "Resource.management_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Resource.status"`)}
	}
	if _, ok := _c.mutation.NodeCount(); !ok {
		return &ValidationError{Name: "node_count", err: errors.New(`ent: missing required field "Resource.node_count"`)}
	}
	if _, ok := _c.mutation.ClientCount(); !ok {
		return &ValidationError{Name: "client_count", err: errors.New(`ent: missing required field "Resource.client_count"`)}
	}
	if _, ok := _c.mutation.SocksCount(); !ok {
		return &ValidationError{Name: "socks_count", err: errors.New(`ent: missing required field "Resource.socks_count"`)}
	}
	if _, ok := _c.mutation.LatencyMs(); !ok {
		return &ValidationError{Name: "latency_ms", err: errors.New(`ent: missing required field "Resource.latency_ms"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Resource.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Resource.updated_at"`)}
	}
	return nil
}

func (_c *ResourceCreate) sqlSave(ctx context.Context) (*Resource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResourceCreate) createSpec() (*Resource, *sqlgraph.CreateSpec) {
	var (
		_node = &Resource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resource.Table, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(resource.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(resource.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Host(); ok {
		_spec.SetField(resource.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := _c.mutation.ManagementURL(); ok {
		_spec.SetField(resource.FieldManagementURL, field.TypeString, value)
		_node.ManagementURL = value
	}
	if value, ok := _c.mutation.AccessTokenCiphertext(); ok {
		_spec.SetField(resource.FieldAccessTokenCiphertext, field.TypeString, value)
		_node.AccessTokenCiphertext = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(resource.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.NodeCount(); ok {
		_spec.SetField(resource.FieldNodeCount, field.TypeInt, value)
		_node.NodeCount = value
	}
	if value, ok := _c.mutation.ClientCount(); ok {
		_spec.SetField(resource.FieldClientCount, field.TypeInt, value)
		_node.ClientCount = value
	}
	if value, ok := _c.mutation.SocksCount(); ok {
		_spec.SetField(resource.FieldSocksCount, field.TypeInt, value)
		_node.SocksCount = value
	}
	if value, ok := _c.mutation.LatencyMs(); ok {
		_spec.SetField(resource.FieldLatencyMs, field.TypeInt, value)
		_node.LatencyMs = value
	}
	if value, ok := _c.mutation.LastCheckedAt(); ok {
		_spec.SetField(resource.FieldLastCheckedAt, field.TypeTime, value)
		_node.LastCheckedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resource.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(resource.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ResourceCreateBulk is the builder for creating many Resource entities in bulk.
type ResourceCreateBulk struct {
	config
	err      error
	builders []*ResourceCreate
}

// Save creates the Resource entities in the database.
func (_c *ResourceCreateBulk) Save(ctx context.Context) ([]*Resource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Resource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResourceCreateBulk) SaveX(ctx context.Context) []*Resource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
