// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/zhou1h/3xui-network-panel-v2/ent/auditlog"
	"github.com/zhou1h/3xui-network-panel-v2/ent/job"
	"github.com/zhou1h/3xui-network-panel-v2/ent/resource"
	"github.com/zhou1h/3xui-network-panel-v2/ent/schema"
	"github.com/zhou1h/3xui-network-panel-v2/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[1].Descriptor()
	// auditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditlog.ActionValidator = auditlogDescAction.Validators[0].(func(string) error)
	// auditlogDescTargetType is the schema descriptor for target_type field.
	auditlogDescTargetType := auditlogFields[2].Descriptor()
	// auditlog.TargetTypeValidator is a validator for the "target_type" field. It is called by the builders before save.
	auditlog.TargetTypeValidator = auditlogDescTargetType.Validators[0].(func(string) error)
	// auditlogDescTargetID is the schema descriptor for target_id field.
	auditlogDescTargetID := auditlogFields[3].Descriptor()
	// auditlog.TargetIDValidator is a validator for the "target_id" field. It is called by the builders before save.
	auditlog.TargetIDValidator = auditlogDescTargetID.Validators[0].(func(string) error)
	// auditlogDescIP is the schema descriptor for ip field.
	auditlogDescIP := auditlogFields[4].Descriptor()
	// auditlog.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	auditlog.IPValidator = auditlogDescIP.Validators[0].(func(string) error)
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogFields[6].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	jobFields := schema.Job{}.Fields()
	_ = jobFields
	// jobDescJobKey is the schema descriptor for job_key field.
	jobDescJobKey := jobFields[0].Descriptor()
	// job.JobKeyValidator is a validator for the "job_key" field. It is called by the builders before save.
	job.JobKeyValidator = jobDescJobKey.Validators[0].(func(string) error)
	// jobDescType is the schema descriptor for type field.
	jobDescType := jobFields[1].Descriptor()
	// job.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	job.TypeValidator = jobDescType.Validators[0].(func(string) error)
	// jobDescStatus is the schema descriptor for status field.
	jobDescStatus := jobFields[2].Descriptor()
	// job.DefaultStatus holds the default value on creation for the status field.
	job.DefaultStatus = jobDescStatus.Default.(string)
	// jobDescProgress is the schema descriptor for progress field.
	jobDescProgress := jobFields[3].Descriptor()
	// job.DefaultProgress holds the default value on creation for the progress field.
	job.DefaultProgress = jobDescProgress.Default.(int)
	// jobDescMessage is the schema descriptor for message field.
	jobDescMessage := jobFields[4].Descriptor()
	// job.MessageValidator is a validator for the "message" field. It is called by the builders before save.
	job.MessageValidator = jobDescMessage.Validators[0].(func(string) error)
	// jobDescCreatedAt is the schema descriptor for created_at field.
	jobDescCreatedAt := jobFields[8].Descriptor()
	// job.DefaultCreatedAt holds the default value on creation for the created_at field.
	job.DefaultCreatedAt = jobDescCreatedAt.Default.(func() time.Time)
	// jobDescUpdatedAt is the schema descriptor for updated_at field.
	jobDescUpdatedAt := jobFields[9].Descriptor()
	// job.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	job.DefaultUpdatedAt = jobDescUpdatedAt.Default.(func() time.Time)
	// job.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	job.UpdateDefaultUpdatedAt = jobDescUpdatedAt.UpdateDefault.(func() time.Time)
	resourceFields := schema.Resource{}.Fields()
	_ = resourceFields
	// resourceDescCode is the schema descriptor for code field.
	resourceDescCode := resourceFields[0].Descriptor()
	// resource.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	resource.CodeValidator = func() func(string) error {
		validators := resourceDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// resourceDescName is the schema descriptor for name field.
	resourceDescName := resourceFields[1].Descriptor()
	// resource.NameValidator is a validator for the "name" field. It is called by the builders before save.
	resource.NameValidator = func() func(string) error {
		validators := resourceDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// resourceDescHost is the schema descriptor for host field.
	resourceDescHost := resourceFields[2].Descriptor()
	// resource.HostValidator is a validator for the "host" field. It is called by the builders before save.
	resource.HostValidator = resourceDescHost.Validators[0].(func(string) error)
	// resourceDescManagementURL is the schema descriptor for management_url field.
	resourceDescManagementURL := resourceFields[3].Descriptor()
	// resource.ManagementURLValidator is a validator for the "management_url" field. It is called by the builders before save.
	resource.ManagementURLValidator = resourceDescManagementURL.Validators[0].(func(string) error)
	// resourceDescStatus is the schema descriptor for status field.
	resourceDescStatus := resourceFields[5].Descriptor()
	// resource.DefaultStatus holds the default value on creation for the status field.
	resource.DefaultStatus = resourceDescStatus.Default.(string)
	// resourceDescNodeCount is the schema descriptor for node_count field.
	resourceDescNodeCount := resourceFields[6].Descriptor()
	// resource.DefaultNodeCount holds the default value on creation for the node_count field.
	resource.DefaultNodeCount = resourceDescNodeCount.Default.(int)
	// resourceDescClientCount is the schema descriptor for client_count field.
	resourceDescClientCount := resourceFields[7].Descriptor()
	// resource.DefaultClientCount holds the default value on creation for the client_count field.
	resource.DefaultClientCount = resourceDescClientCount.Default.(int)
	// resourceDescSocksCount is the schema descriptor for socks_count field.
	resourceDescSocksCount := resourceFields[8].Descriptor()
	// resource.DefaultSocksCount holds the default value on creation for the socks_count field.
	resource.DefaultSocksCount = resourceDescSocksCount.Default.(int)
	// resourceDescLatencyMs is the schema descriptor for latency_ms field.
	resourceDescLatencyMs := resourceFields[9].Descriptor()
	// resource.DefaultLatencyMs holds the default value on creation for the latency_ms field.
	resource.DefaultLatencyMs = resourceDescLatencyMs.Default.(int)
	// resourceDescCreatedAt is the schema descriptor for created_at field.
	resourceDescCreatedAt := resourceFields[11].Descriptor()
	// resource.DefaultCreatedAt holds the default value on creation for the created_at field.
	resource.DefaultCreatedAt = resourceDescCreatedAt.Default.(func() time.Time)
	// resourceDescUpdatedAt is the schema descriptor for updated_at field.
	resourceDescUpdatedAt := resourceFields[12].Descriptor()
	// resource.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	resource.DefaultUpdatedAt = resourceDescUpdatedAt.Default.(func() time.Time)
	// resource.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	resource.UpdateDefaultUpdatedAt = resourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[2].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescEnabled is the schema descriptor for enabled field.
	userDescEnabled := userFields[3].Descriptor()
	// user.DefaultEnabled holds the default value on creation for the enabled field.
	user.DefaultEnabled = userDescEnabled.Default.(bool)
	// userDescMustChangePassword is the schema descriptor for must_change_password field.
	userDescMustChangePassword := userFields[4].Descriptor()
	// user.DefaultMustChangePassword holds the default value on creation for the must_change_password field.
	user.DefaultMustChangePassword = userDescMustChangePassword.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
