// Code generated by ent, DO NOT EDIT.

package resource

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the resource type in the database.
	Label = "resource"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldHost holds the string denoting the host field in the database.
	FieldHost = "host"
	// FieldManagementURL holds the string denoting the management_url field in the database.
	FieldManagementURL = "management_url"
	// FieldAccessTokenCiphertext holds the string denoting the access_token_ciphertext field in the database.
	FieldAccessTokenCiphertext = "access_token_ciphertext"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNodeCount holds the string denoting the node_count field in the database.
	FieldNodeCount = "node_count"
	// FieldClientCount holds the string denoting the client_count field in the database.
	FieldClientCount = "client_count"
	// FieldSocksCount holds the string denoting the socks_count field in the database.
	FieldSocksCount = "socks_count"
	// FieldLatencyMs holds the string denoting the latency_ms field in the database.
	FieldLatencyMs = "latency_ms"
	// FieldLastCheckedAt holds the string denoting the last_checked_at field in the database.
	FieldLastCheckedAt = "last_checked_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the resource in the database.
	Table = "resources"
)

// Columns holds all SQL columns for resource fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldName,
	FieldHost,
	FieldManagementURL,
	FieldAccessTokenCiphertext,
	FieldStatus,
	FieldNodeCount,
	FieldClientCount,
	FieldSocksCount,
	FieldLatencyMs,
	FieldLastCheckedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// HostValidator is a validator for the "host" field. It is called by the builders before save.
	HostValidator func(string) error
	// ManagementURLValidator is a validator for the "management_url" field. It is called by the builders before save.
	ManagementURLValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultNodeCount holds the default value on creation for the "node_count" field.
	DefaultNodeCount int
	// DefaultClientCount holds the default value on creation for the "client_count" field.
	DefaultClientCount int
	// DefaultSocksCount holds the default value on creation for the "socks_count" field.
	DefaultSocksCount int
	// DefaultLatencyMs holds the default value on creation for the "latency_ms" field.
	DefaultLatencyMs int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Resource queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByHost orders the results by the host field.
func ByHost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHost, opts...).ToFunc()
}

// ByManagementURL orders the results by the management_url field.
func ByManagementURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManagementURL, opts...).ToFunc()
}

// ByAccessTokenCiphertext orders the results by the access_token_ciphertext field.
func ByAccessTokenCiphertext(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessTokenCiphertext, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNodeCount orders the results by the node_count field.
func ByNodeCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeCount, opts...).ToFunc()
}

// ByClientCount orders the results by the client_count field.
func ByClientCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientCount, opts...).ToFunc()
}

// BySocksCount orders the results by the socks_count field.
func BySocksCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSocksCount, opts...).ToFunc()
}

// ByLatencyMs orders the results by the latency_ms field.
func ByLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatencyMs, opts...).ToFunc()
}

// ByLastCheckedAt orders the results by the last_checked_at field.
func ByLastCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCheckedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
