// Code generated by ent, DO NOT EDIT.

package resource

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/zhou1h/3xui-network-panel-v2/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Resource {
	return predicate.Resource(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Resource {
	return predicate.Resource(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Resource {
	return predicate.Resource(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Resource {
	return predicate.Resource(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Resource {
	return predicate.Resource(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Resource {
	return predicate.Resource(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Resource {
	return predicate.Resource(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldName, v))
}

// Host applies equality check predicate on the "host" field. It's identical to HostEQ.
func Host(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldHost, v))
}

// ManagementURL applies equality check predicate on the "management_url" field. It's identical to ManagementURLEQ.
func ManagementURL(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldManagementURL, v))
}

// AccessTokenCiphertext applies equality check predicate on the "access_token_ciphertext" field. It's identical to AccessTokenCiphertextEQ.
func AccessTokenCiphertext(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldAccessTokenCiphertext, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldStatus, v))
}

// NodeCount applies equality check predicate on the "node_count" field. It's identical to NodeCountEQ.
func NodeCount(v int) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldNodeCount, v))
}

// ClientCount applies equality check predicate on the "client_count" field. It's identical to ClientCountEQ.
func ClientCount(v int) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldClientCount, v))
}

// SocksCount applies equality check predicate on the "socks_count" field. It's identical to SocksCountEQ.
func SocksCount(v int) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldSocksCount, v))
}

// LatencyMs applies equality check predicate on the "latency_ms" field. It's identical to LatencyMsEQ.
func LatencyMs(v int) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldLatencyMs, v))
}

// LastCheckedAt applies equality check predicate on the "last_checked_at" field. It's identical to LastCheckedAtEQ.
func LastCheckedAt(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldLastCheckedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldUpdatedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.Resource {
	return predicate.Resource(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.Resource {
	return predicate.Resource(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.Resource {
	return predicate.Resource(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.Resource {
	return predicate.Resource(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.Resource {
	return predicate.Resource(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.Resource {
	return predicate.Resource(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.Resource {
	return predicate.Resource(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.Resource {
	return predicate.Resource(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.Resource {
	return predicate.Resource(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.Resource {
	return predicate.Resource(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.Resource {
	return predicate.Resource(sql.FieldContainsFold(FieldCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Resource {
	return predicate.Resource(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Resource {
	return predicate.Resource(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Resource {
	return predicate.Resource(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Resource {
	return predicate.Resource(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Resource {
	return predicate.Resource(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Resource {
	return predicate.Resource(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Resource {
	return predicate.Resource(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Resource {
	return predicate.Resource(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Resource {
	return predicate.Resource(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Resource {
	return predicate.Resource(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Resource {
	return predicate.Resource(sql.FieldContainsFold(FieldName, v))
}

// HostEQ applies the EQ predicate on the "host" field.
func HostEQ(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldHost, v))
}

// HostNEQ applies the NEQ predicate on the "host" field.
func HostNEQ(v string) predicate.Resource {
	return predicate.Resource(sql.FieldNEQ(FieldHost, v))
}

// HostIn applies the In predicate on the "host" field.
func HostIn(vs ...string) predicate.Resource {
	return predicate.Resource(sql.FieldIn(FieldHost, vs...))
}

// HostNotIn applies the NotIn predicate on the "host" field.
func HostNotIn(vs ...string) predicate.Resource {
	return predicate.Resource(sql.FieldNotIn(FieldHost, vs...))
}

// HostGT applies the GT predicate on the "host" field.
func HostGT(v string) predicate.Resource {
	return predicate.Resource(sql.FieldGT(FieldHost, v))
}

// HostGTE applies the GTE predicate on the "host" field.
func HostGTE(v string) predicate.Resource {
	return predicate.Resource(sql.FieldGTE(FieldHost, v))
}

// HostLT applies the LT predicate on the "host" field.
func HostLT(v string) predicate.Resource {
	return predicate.Resource(sql.FieldLT(FieldHost, v))
}

// HostLTE applies the LTE predicate on the "host" field.
func HostLTE(v string) predicate.Resource {
	return predicate.Resource(sql.FieldLTE(FieldHost, v))
}

// HostContains applies the Contains predicate on the "host" field.
func HostContains(v string) predicate.Resource {
	return predicate.Resource(sql.FieldContains(FieldHost, v))
}

// HostHasPrefix applies the HasPrefix predicate on the "host" field.
func HostHasPrefix(v string) predicate.Resource {
	return predicate.Resource(sql.FieldHasPrefix(FieldHost, v))
}

// HostHasSuffix applies the HasSuffix predicate on the "host" field.
func HostHasSuffix(v string) predicate.Resource {
	return predicate.Resource(sql.FieldHasSuffix(FieldHost, v))
}

// HostEqualFold applies the EqualFold predicate on the "host" field.
func HostEqualFold(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEqualFold(FieldHost, v))
}

// HostContainsFold applies the ContainsFold predicate on the "host" field.
func HostContainsFold(v string) predicate.Resource {
	return predicate.Resource(sql.FieldContainsFold(FieldHost, v))
}

// ManagementURLEQ applies the EQ predicate on the "management_url" field.
func ManagementURLEQ(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldManagementURL, v))
}

// ManagementURLNEQ applies the NEQ predicate on the "management_url" field.
func ManagementURLNEQ(v string) predicate.Resource {
	return predicate.Resource(sql.FieldNEQ(FieldManagementURL, v))
}

// ManagementURLIn applies the In predicate on the "management_url" field.
func ManagementURLIn(vs ...string) predicate.Resource {
	return predicate.Resource(sql.FieldIn(FieldManagementURL, vs...))
}

// ManagementURLNotIn applies the NotIn predicate on the "management_url" field.
func ManagementURLNotIn(vs ...string) predicate.Resource {
	return predicate.Resource(sql.FieldNotIn(FieldManagementURL, vs...))
}

// ManagementURLGT applies the GT predicate on the "management_url" field.
func ManagementURLGT(v string) predicate.Resource {
	return predicate.Resource(sql.FieldGT(FieldManagementURL, v))
}

// ManagementURLGTE applies the GTE predicate on the "management_url" field.
func ManagementURLGTE(v string) predicate.Resource {
	return predicate.Resource(sql.FieldGTE(FieldManagementURL, v))
}

// ManagementURLLT applies the LT predicate on the "management_url" field.
func ManagementURLLT(v string) predicate.Resource {
	return predicate.Resource(sql.FieldLT(FieldManagementURL, v))
}

// ManagementURLLTE applies the LTE predicate on the "management_url" field.
func ManagementURLLTE(v string) predicate.Resource {
	return predicate.Resource(sql.FieldLTE(FieldManagementURL, v))
}

// ManagementURLContains applies the Contains predicate on the "management_url" field.
func ManagementURLContains(v string) predicate.Resource {
	return predicate.Resource(sql.FieldContains(FieldManagementURL, v))
}

// ManagementURLHasPrefix applies the HasPrefix predicate on the "management_url" field.
func ManagementURLHasPrefix(v string) predicate.Resource {
	return predicate.Resource(sql.FieldHasPrefix(FieldManagementURL, v))
}

// ManagementURLHasSuffix applies the HasSuffix predicate on the "management_url" field.
func ManagementURLHasSuffix(v string) predicate.Resource {
	return predicate.Resource(sql.FieldHasSuffix(FieldManagementURL, v))
}

// ManagementURLIsNil applies the IsNil predicate on the "management_url" field.
func ManagementURLIsNil() predicate.Resource {
	return predicate.Resource(sql.FieldIsNull(FieldManagementURL))
}

// ManagementURLNotNil applies the NotNil predicate on the "management_url" field.
func ManagementURLNotNil() predicate.Resource {
	return predicate.Resource(sql.FieldNotNull(FieldManagementURL))
}

// ManagementURLEqualFold applies the EqualFold predicate on the "management_url" field.
func ManagementURLEqualFold(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEqualFold(FieldManagementURL, v))
}

// ManagementURLContainsFold applies the ContainsFold predicate on the "management_url" field.
func ManagementURLContainsFold(v string) predicate.Resource {
	return predicate.Resource(sql.FieldContainsFold(FieldManagementURL, v))
}

// AccessTokenCiphertextEQ applies the EQ predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextEQ(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextNEQ applies the NEQ predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextNEQ(v string) predicate.Resource {
	return predicate.Resource(sql.FieldNEQ(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextIn applies the In predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextIn(vs ...string) predicate.Resource {
	return predicate.Resource(sql.FieldIn(FieldAccessTokenCiphertext, vs...))
}

// AccessTokenCiphertextNotIn applies the NotIn predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextNotIn(vs ...string) predicate.Resource {
	return predicate.Resource(sql.FieldNotIn(FieldAccessTokenCiphertext, vs...))
}

// AccessTokenCiphertextGT applies the GT predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextGT(v string) predicate.Resource {
	return predicate.Resource(sql.FieldGT(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextGTE applies the GTE predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextGTE(v string) predicate.Resource {
	return predicate.Resource(sql.FieldGTE(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextLT applies the LT predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextLT(v string) predicate.Resource {
	return predicate.Resource(sql.FieldLT(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextLTE applies the LTE predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextLTE(v string) predicate.Resource {
	return predicate.Resource(sql.FieldLTE(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextContains applies the Contains predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextContains(v string) predicate.Resource {
	return predicate.Resource(sql.FieldContains(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextHasPrefix applies the HasPrefix predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextHasPrefix(v string) predicate.Resource {
	return predicate.Resource(sql.FieldHasPrefix(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextHasSuffix applies the HasSuffix predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextHasSuffix(v string) predicate.Resource {
	return predicate.Resource(sql.FieldHasSuffix(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextIsNil applies the IsNil predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextIsNil() predicate.Resource {
	return predicate.Resource(sql.FieldIsNull(FieldAccessTokenCiphertext))
}

// AccessTokenCiphertextNotNil applies the NotNil predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextNotNil() predicate.Resource {
	return predicate.Resource(sql.FieldNotNull(FieldAccessTokenCiphertext))
}

// AccessTokenCiphertextEqualFold applies the EqualFold predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextEqualFold(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEqualFold(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextContainsFold applies the ContainsFold predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextContainsFold(v string) predicate.Resource {
	return predicate.Resource(sql.FieldContainsFold(FieldAccessTokenCiphertext, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Resource {
	return predicate.Resource(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Resource {
	return predicate.Resource(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Resource {
	return predicate.Resource(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Resource {
	return predicate.Resource(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Resource {
	return predicate.Resource(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Resource {
	return predicate.Resource(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Resource {
	return predicate.Resource(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Resource {
	return predicate.Resource(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Resource {
	return predicate.Resource(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Resource {
	return predicate.Resource(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Resource {
	return predicate.Resource(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Resource {
	return predicate.Resource(sql.FieldContainsFold(FieldStatus, v))
}

// NodeCountEQ applies the EQ predicate on the "node_count" field.
func NodeCountEQ(v int) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldNodeCount, v))
}

// NodeCountNEQ applies the NEQ predicate on the "node_count" field.
func NodeCountNEQ(v int) predicate.Resource {
	return predicate.Resource(sql.FieldNEQ(FieldNodeCount, v))
}

// NodeCountIn applies the In predicate on the "node_count" field.
func NodeCountIn(vs ...int) predicate.Resource {
	return predicate.Resource(sql.FieldIn(FieldNodeCount, vs...))
}

// NodeCountNotIn applies the NotIn predicate on the "node_count" field.
func NodeCountNotIn(vs ...int) predicate.Resource {
	return predicate.Resource(sql.FieldNotIn(FieldNodeCount, vs...))
}

// NodeCountGT applies the GT predicate on the "node_count" field.
func NodeCountGT(v int) predicate.Resource {
	return predicate.Resource(sql.FieldGT(FieldNodeCount, v))
}

// NodeCountGTE applies the GTE predicate on the "node_count" field.
func NodeCountGTE(v int) predicate.Resource {
	return predicate.Resource(sql.FieldGTE(FieldNodeCount, v))
}

// NodeCountLT applies the LT predicate on the "node_count" field.
func NodeCountLT(v int) predicate.Resource {
	return predicate.Resource(sql.FieldLT(FieldNodeCount, v))
}

// NodeCountLTE applies the LTE predicate on the "node_count" field.
func NodeCountLTE(v int) predicate.Resource {
	return predicate.Resource(sql.FieldLTE(FieldNodeCount, v))
}

// ClientCountEQ applies the EQ predicate on the "client_count" field.
func ClientCountEQ(v int) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldClientCount, v))
}

// ClientCountNEQ applies the NEQ predicate on the "client_count" field.
func ClientCountNEQ(v int) predicate.Resource {
	return predicate.Resource(sql.FieldNEQ(FieldClientCount, v))
}

// ClientCountIn applies the In predicate on the "client_count" field.
func ClientCountIn(vs ...int) predicate.Resource {
	return predicate.Resource(sql.FieldIn(FieldClientCount, vs...))
}

// ClientCountNotIn applies the NotIn predicate on the "client_count" field.
func ClientCountNotIn(vs ...int) predicate.Resource {
	return predicate.Resource(sql.FieldNotIn(FieldClientCount, vs...))
}

// ClientCountGT applies the GT predicate on the "client_count" field.
func ClientCountGT(v int) predicate.Resource {
	return predicate.Resource(sql.FieldGT(FieldClientCount, v))
}

// ClientCountGTE applies the GTE predicate on the "client_count" field.
func ClientCountGTE(v int) predicate.Resource {
	return predicate.Resource(sql.FieldGTE(FieldClientCount, v))
}

// ClientCountLT applies the LT predicate on the "client_count" field.
func ClientCountLT(v int) predicate.Resource {
	return predicate.Resource(sql.FieldLT(FieldClientCount, v))
}

// ClientCountLTE applies the LTE predicate on the "client_count" field.
func ClientCountLTE(v int) predicate.Resource {
	return predicate.Resource(sql.FieldLTE(FieldClientCount, v))
}

// SocksCountEQ applies the EQ predicate on the "socks_count" field.
func SocksCountEQ(v int) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldSocksCount, v))
}

// SocksCountNEQ applies the NEQ predicate on the "socks_count" field.
func SocksCountNEQ(v int) predicate.Resource {
	return predicate.Resource(sql.FieldNEQ(FieldSocksCount, v))
}

// SocksCountIn applies the In predicate on the "socks_count" field.
func SocksCountIn(vs ...int) predicate.Resource {
	return predicate.Resource(sql.FieldIn(FieldSocksCount, vs...))
}

// SocksCountNotIn applies the NotIn predicate on the "socks_count" field.
func SocksCountNotIn(vs ...int) predicate.Resource {
	return predicate.Resource(sql.FieldNotIn(FieldSocksCount, vs...))
}

// SocksCountGT applies the GT predicate on the "socks_count" field.
func SocksCountGT(v int) predicate.Resource {
	return predicate.Resource(sql.FieldGT(FieldSocksCount, v))
}

// SocksCountGTE applies the GTE predicate on the "socks_count" field.
func SocksCountGTE(v int) predicate.Resource {
	return predicate.Resource(sql.FieldGTE(FieldSocksCount, v))
}

// SocksCountLT applies the LT predicate on the "socks_count" field.
func SocksCountLT(v int) predicate.Resource {
	return predicate.Resource(sql.FieldLT(FieldSocksCount, v))
}

// SocksCountLTE applies the LTE predicate on the "socks_count" field.
func SocksCountLTE(v int) predicate.Resource {
	return predicate.Resource(sql.FieldLTE(FieldSocksCount, v))
}

// LatencyMsEQ applies the EQ predicate on the "latency_ms" field.
func LatencyMsEQ(v int) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldLatencyMs, v))
}

// LatencyMsNEQ applies the NEQ predicate on the "latency_ms" field.
func LatencyMsNEQ(v int) predicate.Resource {
	return predicate.Resource(sql.FieldNEQ(FieldLatencyMs, v))
}

// LatencyMsIn applies the In predicate on the "latency_ms" field.
func LatencyMsIn(vs ...int) predicate.Resource {
	return predicate.Resource(sql.FieldIn(FieldLatencyMs, vs...))
}

// LatencyMsNotIn applies the NotIn predicate on the "latency_ms" field.
func LatencyMsNotIn(vs ...int) predicate.Resource {
	return predicate.Resource(sql.FieldNotIn(FieldLatencyMs, vs...))
}

// LatencyMsGT applies the GT predicate on the "latency_ms" field.
func LatencyMsGT(v int) predicate.Resource {
	return predicate.Resource(sql.FieldGT(FieldLatencyMs, v))
}

// LatencyMsGTE applies the GTE predicate on the "latency_ms" field.
func LatencyMsGTE(v int) predicate.Resource {
	return predicate.Resource(sql.FieldGTE(FieldLatencyMs, v))
}

// LatencyMsLT applies the LT predicate on the "latency_ms" field.
func LatencyMsLT(v int) predicate.Resource {
	return predicate.Resource(sql.FieldLT(FieldLatencyMs, v))
}

// LatencyMsLTE applies the LTE predicate on the "latency_ms" field.
func LatencyMsLTE(v int) predicate.Resource {
	return predicate.Resource(sql.FieldLTE(FieldLatencyMs, v))
}

// LastCheckedAtEQ applies the EQ predicate on the "last_checked_at" field.
func LastCheckedAtEQ(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtNEQ applies the NEQ predicate on the "last_checked_at" field.
func LastCheckedAtNEQ(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldNEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtIn applies the In predicate on the "last_checked_at" field.
func LastCheckedAtIn(vs ...time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtNotIn applies the NotIn predicate on the "last_checked_at" field.
func LastCheckedAtNotIn(vs ...time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldNotIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtGT applies the GT predicate on the "last_checked_at" field.
func LastCheckedAtGT(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldGT(FieldLastCheckedAt, v))
}

// LastCheckedAtGTE applies the GTE predicate on the "last_checked_at" field.
func LastCheckedAtGTE(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldGTE(FieldLastCheckedAt, v))
}

// LastCheckedAtLT applies the LT predicate on the "last_checked_at" field.
func LastCheckedAtLT(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldLT(FieldLastCheckedAt, v))
}

// LastCheckedAtLTE applies the LTE predicate on the "last_checked_at" field.
func LastCheckedAtLTE(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldLTE(FieldLastCheckedAt, v))
}

// LastCheckedAtIsNil applies the IsNil predicate on the "last_checked_at" field.
func LastCheckedAtIsNil() predicate.Resource {
	return predicate.Resource(sql.FieldIsNull(FieldLastCheckedAt))
}

// LastCheckedAtNotNil applies the NotNil predicate on the "last_checked_at" field.
func LastCheckedAtNotNil() predicate.Resource {
	return predicate.Resource(sql.FieldNotNull(FieldLastCheckedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Resource {
	return predicate.Resource(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Resource) predicate.Resource {
	return predicate.Resource(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Resource) predicate.Resource {
	return predicate.Resource(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Resource) predicate.Resource {
	return predicate.Resource(sql.NotPredicates(p))
}
