// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// Job is the predicate function for job builders.
type Job func(*sql.Selector)

// Resource is the predicate function for resource builders.
type Resource func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
